package model;

public enum BetType {
    BLACKJACK, HORSE_RACE_PURPLE, HORSE_RACE_RED, HORSE_RACE_BLUE,
    ROULETTE_0,ROULETTE_1, ROULETTE_2, ROULETTE_3, ROULETTE_4, ROULETTE_5, ROULETTE_6,ROULETTE_7,
    ROULETTE_8,ROULETTE_9, ROULETTE_10, ROULETTE_11, ROULETTE_12, ROULETTE_13, ROULETTE_14,ROULETTE_15,
    ROULETTE_16,ROULETTE_17, ROULETTE_18, ROULETTE_19, ROULETTE_20, ROULETTE_21, ROULETTE_22,ROULETTE_23,
    ROULETTE_24,ROULETTE_25, ROULETTE_26, ROULETTE_27, ROULETTE_28, ROULETTE_29, ROULETTE_30,ROULETTE_31,
    ROULETTE_32,ROULETTE_33, ROULETTE_34, ROULETTE_35, ROULETTE_36, ROULETTE_EVEN, ROULETTE_ODD,ROULETTE_RED,
    ROULETTE_BLACK,ROULETTE_FIRST_12, ROULETTE_SECOND_12, ROULETTE_THIRD_12, ROULETTE_FIRST_ROW, ROULETTE_SECOND_ROW,
    ROULETTE_THIRD_ROW, ROULETTE_1_18,ROULETTE_19_36
}
